### ISSUE TITLE
Register Page 

### ISSUE THREAD

**Issue by jonthemango** [Kerry-G/SOEN341-UB2#2]
Front-End of Register Page needs to be done using React. Should have a form that allows users to enter information such as first and last name, email, password and engineering discipline.

Route: `/register`

**Comment by Kerry-G** [comment]
The structure is done. I haven't done any CSS though.

**Comment by sharon-ho** [comment]
I can do the CSS for the page! There is a good open source CSS stylesheet by W3 schools that I use, and it acts like Bootstrap even though it's pure CSS.

**Comment by Kerry-G** [comment]
@sharon-ho Checkout feature/registerModal, I use [react-boostrap ](https://react-bootstrap.github.io/getting-started/introduction )which makes bootstrap a little bit less cumbersome/easier-to-read  in react.js. 

However, you can always add regular css to any component by adding the props "className" to it. In react.js, it is not bad pratice to do in-line styling either. If you want an exemple of that, check Header.js. Lastly, you can over-ride react-bootstrap with the props "bsClass"

**Comment by sharon-ho** [comment]
@Kerry-G Great, I'll check it out. Thanks for all the info Kerry!

**Comment by ramzouza** [comment]
Register page has been completed as a 3 part modal
