### ISSUE TITLE
Assign QA's 

### ISSUE THREAD

**Issue by jonthemango** [Kerry-G/SOEN341-UB2#3]
Someone should go on every page that is live once home and register are deployed and try everything in their power to break them. We need to fix all possible bugs so the best way is to try to break stuff (through the UI not the code).

**Comment by Kerry-G** [comment]
Maybe we should assign someone on QA duty?

**Comment by Kerry-G** [comment]
Is there any one of you that volunteer for this?

@linkmarche @Megan-VanHumbeck @niko378 @ramzouza @sharon-ho @JamalG16

**Comment by Megan-VanHumbeck** [comment]
I can do it!

**Comment by jonthemango** [comment]
Sounds good!

**Comment by Kerry-G** [comment]
Since this issue is resolved, i'll close the thread.
