### ISSUE TITLE
Register new User

### ISSUE THREAD

**Issue by jonthemango** [Kerry-G/SOEN341-UB2#5]
The front-end will send the 'new user' request (user and password) to the flask api. The request will be handled. First we will check whether a user with those credentials exist. If not then we create that user using Users model. A JSON response will be returned to the front-end with 3 properties: `{'success':` bool, 'message': str , 'status': str}`

**Comment by jonthemango** [comment]
Since I already started this in the environment setup. I'll own this.

**Comment by Kerry-G** [comment]
I started a new feature for it and made a modal for registration. Looks fine but when I try to save on the database python tells me

`sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.engineer [SQL: 'INSERT INTO user (fname, lname, email, password_hash, register_date, engineer, display_image, verified, ups, downs) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('test', 'test', 'test@test.com', '$5$rounds=535000$lEFrsuY2e/wPHFEU$FDsXtpW0wtu1rWw3l1NrSgO8C9OcNsc6yqdZFxXMQs0', '2018-01-30 21:23:07.099663', 'software', '/public/images/avatar/1.png', 0, 0, 0)] (Background on this error at: http://sqlalche.me/e/gkpj)`

**Comment by jonthemango** [comment]
Master can now register users.
